/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_capstone_androidrecovery_nativeclass_NativeDeviceList */

#ifndef _Included_edu_handong_ghost_ctrlz_nativeclass_NativeDeviceList
#define _Included_edu_handong_ghost_ctrlz_nativeclass_NativeDeviceList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_handong_ghost_ctrlz_nativeclass_NativeDeviceList
 * Method:    getDeviceList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_edu_handong_ghost_ctrlz_nativeclass_NativeDeviceList_getDeviceList__
  (JNIEnv *, jobject);

/*
 * Class:     edu_handong_ghost_ctrlz_nativeclass_NativeDeviceList
 * Method:    getDeviceList
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_edu_handong_ghost_ctrlz_nativeclass_NativeDeviceList_getDeviceList__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
